# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_ldconfig'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Manage /etc/ld.so.conf'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'fedora'
supports 'redhat'
depends 'fb_helpers'
