# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_sysctl'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Configures sysctl'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'mac_os_x'
supports 'ubuntu'
depends 'fb_helpers'
