driver:
  name: dokken
  privileged: true
  # our cookbooks should be compatible with the latest Chef,
  # but we nee to ensure they still work on 13 until we move to 14
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

platforms:
  - name: centos-stream-9
    driver:
      image: dokken/centos-stream-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  - name: centos-stream-10
    driver:
      image: dokken/centos-stream-10
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # mirrorlist.centos.org doesn't exist anymore, use baseurl
        - RUN sed -i=.bak -e 's/^mirrorlist/#mirrorlist/g' -e 's!^#baseurl=http://mirror.centos.org/$contentdir/$stream!baseurl=https://vault.centos.org/$stream!g' /etc/yum.repos.d/*.repo
        - RUN rm /etc/yum.repos.d/*.bak
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd

provisioner:
  name: dokken
  chef_log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

transport:
  name: dokken

suites:
  - name: default
    run_list:
      - recipe[ci_fixes]
      - recipe[fb_init_sample]
      - recipe[test_services]
