driver:
  name: docker
  privileged: true

platforms:
  - name: centos-6
    driver_config:
      provision_command:
        # stub out /etc/fstab for fb_fstab
        - touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  - name: centos-7
    driver_config:
      provision_command:
        # stub out /etc/fstab for fb_fstab
        - touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      run_command: /usr/sbin/init
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init
  - name: debian-8
    driver_config:
      provision_command:
        # https://github.com/test-kitchen/test-kitchen/issues/1018
        # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814070
        - apt-get install -y wget
      run_command: /sbin/init
  - name: debian-sid
    driver_config:
      run_command: /bin/systemd

provisioner:
  name: chef_zero

suites:
  - name: default
    run_list:
      - recipe[fb_init_sample]
      - recipe[fb_apcupsd]
      - recipe[fb_collectd]
      - recipe[fb_dnsmasq]
      - recipe[fb_hddtemp]
      - recipe[fb_vsftpd]
    excludes: centos-6
  - name: default-centos-6
    run_list:
      - recipe[fb_init_sample]
      - recipe[fb_collectd]
      - recipe[fb_dnsmasq]
      - recipe[fb_hddtemp]
      - recipe[fb_vsftpd]
    includes: centos-6
