driver:
  name: dokken
  privileged: true
  # our cookbooks should be compatible with the latest Chef,
  # but we nee to ensure they still work on 13 until we move to 14
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

platforms:
  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
      intermediate_instructions:
        # remove bogus entry to make fb_fstab happy
        - RUN sed -i '/UUID=/d' /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_commmand: /bin/systemd

provisioner:
  name: dokken
  chef_log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

transport:
  name: dokken

suites:
  - name: default
    run_list:
      - recipe[ci_fixes]
      - recipe[fb_init_sample]
      - recipe[test_services]
