# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_ipc'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Controls shared memory segments'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
supports 'debian'
supports 'ubuntu'
