# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_dracut'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Installs/Configures dracut'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
supports 'fedora'
supports 'redhat'
depends 'fb_helpers'
