# Copyright (c) 2013-present, Facebook, Inc.
name 'fb_sysstat'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Configuration for sysstat'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
depends 'fb_helpers'
