# Copyright (c) 2019-present, Facebook, Inc.
name 'fb_less'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Configures less'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'
depends 'fb_helpers'
