# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_limits'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Installs/Configures /etc/security/limits.conf'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'oracle'
supports 'redhat'
supports 'ubuntu'
depends 'fb_helpers'
