# Copyright (c) 2016-present, Facebook, Inc.
name 'fb_swap'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Controls swap enable/disable'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
supports 'debian'
supports 'ubuntu'
depends 'fb_dracut'
depends 'fb_fstab'
depends 'fb_helpers'
depends 'fb_systemd'
