# Copyright (c) 2018-present, Facebook, Inc.
name 'ci_fixes'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Misc fixes to make the CI work'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'ubuntu'
depends 'chef_json_recipes_backport'
depends 'fb_helpers'
