# Copyright (c) 2021-present, Facebook, Inc.
name 'fb_smartctl'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
source_url 'https://github.com/facebook/chef-cookbooks/'
license 'Apache-2.0'
description 'Smartctl install and configuration'
version '0.0.1'
depends 'fb_helpers'
supports 'mac_os_x'
