#!/bin/sh
#
# vim: syntax=ruby:expandtab:shiftwidth=2:softtabstop=2:tabstop=2
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

default_config='.rubocop.yml'
if bundle exec rubocop --version > /dev/null 2>&1; then
  RUBOCOP='bundle exec rubocop'
elif [ -x /opt/chef-workstation/embedded/bin/rubocop ]; then
  RUBOCOP='/opt/chef-workstation/embedded/bin/rubocop'
elif [ -x /opt/chefdk/embedded/bin/rubocop ]; then
  RUBOCOP='/opt/chefdk/embedded/bin/rubocop'
  default_config='.rubocop_55.yml'
elif [ -x /opt/chef/embedded/bin/rubocop ]; then
  RUBOCOP='/opt/chef/embedded/bin/rubocop'
else
  echo 'Cannot find rubocop!'
  exit 1
fi

if [ "$#" -eq 0 ]; then
  config="$default_config"
elif [ "$#" -eq 1 ]; then
  config="$1"
else
  echo "Usage: $0 [config]"
  exit 1
fi

if [ ! -r "$config" ]; then
  echo "Cannot read rubocop config: $config"
  exit 1
fi

exec $RUBOCOP --display-cop-names -c "$config"
