#!/bin/sh
#
# vim: syntax=ruby:expandtab:shiftwidth=2:softtabstop=2:tabstop=2
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

# excluded rules
# FC014 - long ruby blocks
# FC017 - LWRP does not notify
# FC024 - platform equivs
# FC059 - LWRP does not use_inline_resoures
# FC064 - issues URL - same as source_url, come on
# FC066 - ensure chef_version is set in metadata
# FC071 - missing LICENSE file
# FC085 - using new_resource.updated_by_last_action to converge
# FC094 - this is wrong advice before 13
# FC113 - will fix this as part of Chef 13 migration
excluded_rules='FC014 FC017 FC024 FC059 FC064 FC066 FC071 FC085 FC094 FC113'
# shellcheck disable=SC2039
exclude_flags=$(for r in $excluded_rules; do echo "-t ~$r"; done)

if bundle exec foodcritic --version > /dev/null 2>&1; then
  echo 'Using bundled foodcritic'
  FOODCRITIC='bundle exec foodcritic'
elif [ -x /opt/chef-workstation/embedded/bin/foodcritic ]; then
  echo 'Falling back to chef-workstation foodcritic'
  FOODCRITIC='/opt/chef-workstation/embedded/bin/foodcritic'
elif [ -x /opt/chefdk/embedded/bin/foodcritic ]; then
  echo 'Falling back to chefdk foodcritic'
  FOODCRITIC='/opt/chefdk/embedded/bin/foodcritic'
elif [ -x /opt/chef/embedded/bin/foodcritic ]; then
  echo 'Falling back to chef foodcritic'
  FOODCRITIC='/opt/chef/embedded/bin/foodcritic'
else
  echo 'Cannot find foodcritic!'
  echo 'bundle exec foodcritic --version output:'
  bundle exec foodcritic --version
  exit 1
fi

# shellcheck disable=SC2086
exec $FOODCRITIC -f any $exclude_flags cookbooks
