#!/bin/bash

if [ -z "$SKEY" ]; then
  SKEY='../supermarket.pem'
fi
if [ -z "$SUSER" ]; then
  SUSER='phild'
fi

COMMON_OPTS="-m https://supermarket.chef.io -k $SKEY -u $SUSER"

rvm "$TRAVIS_RUBY_VERSION" do bundle install
cd cookbooks
for i in *; do
  echo "Unpublishing $i"
  rvm "$TRAVIS_RUBY_VERSION" do bundle exec \
    knife cookbook site unshare $i $COMMON_OPTS -y
  echo "Publishing $i"
  rvm "$TRAVIS_RUBY_VERSION" do bundle exec \
    knife cookbook site share $i Other -o . $COMMON_OPTS
done
