# Copyright (c) 2020-present, Facebook, Inc.
name 'fb_networksetup'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
source_url 'https://github.com/facebook/chef-cookbooks/'
license 'Apache-2.0'
description 'Installs/Configures networking'
version '0.0.1'
supports 'mac_os_x'
depends 'fb_helpers'
