# Copyright (c) 2019-present, Facebook, Inc.
name 'fb_grubby'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Used to manage GRUB configuration'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'fedora'
depends 'fb_helpers'
