# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_init_sample'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Setup a base runlist for using Facebook cookbooks'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.0.1'
%w{
  centos
  debian
  ubuntu
}.each do |p|
  supports p
end
depends 'fb_apcupsd'
depends 'fb_apt'
depends 'fb_chrony'
depends 'fb_collectd'
depends 'fb_cron'
depends 'fb_dnsmasq'
depends 'fb_dracut'
depends 'fb_e2fsprogs'
depends 'fb_ebtables'
depends 'fb_ethers'
depends 'fb_ethtool'
depends 'fb_fstab'
depends 'fb_grub'
depends 'fb_grubby'
depends 'fb_hddtemp'
depends 'fb_hdparm'
depends 'fb_helpers'
depends 'fb_hostconf'
depends 'fb_hostname'
depends 'fb_hosts'
# no recipe but we want the provider included
# for the tests
depends 'fb_ipc'
depends 'fb_iproute'
depends 'fb_ipset'
depends 'fb_iptables'
depends 'fb_launchd'
depends 'fb_ldconfig'
depends 'fb_less'
depends 'fb_limits'
depends 'fb_logrotate'
depends 'fb_mlocate'
depends 'fb_modprobe'
depends 'fb_motd'
depends 'fb_networkmanager'
depends 'fb_nscd'
depends 'fb_nsswitch'
depends 'fb_postfix'
depends 'fb_profile'
depends 'fb_rpm'
depends 'fb_rsync'
depends 'fb_screen'
depends 'fb_sdparm'
depends 'fb_securetty'
depends 'fb_smartmon'
depends 'fb_storage'
depends 'fb_stunnel'
depends 'fb_sudo'
depends 'fb_swap'
depends 'fb_sysctl'
# no recipe but we want the provider included
# for the tests
depends 'fb_sysfs'
depends 'fb_syslog'
depends 'fb_sysstat'
depends 'fb_systemd'
depends 'fb_timers'
depends 'fb_tmpclean'
depends 'fb_users'
depends 'fb_util_linux'
