# Copyright (c) 2019-present, Facebook, Inc.
name 'fb_chrony'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Installs/Configures Chronyd'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
supports 'debian'
supports 'fedora'
support  'oracle'
supports 'redhat'
supports 'rocky'
supports 'ubuntu'
depends 'fb_helpers'
