# Copyright (c) 2016-present, Facebook, Inc.
name 'fb_jq'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Installs/Configures jq'
source_url 'https://github.com/facebook/chef-cookbooks/'
version '0.1.0'
supports 'centos'
depends 'fb_helpers'
