# Copyright (c) 2018-present, Facebook, Inc.
name 'fb_postfix'
maintainer 'Facebook'
maintainer_email 'noreply@facebook.com'
license 'Apache-2.0'
description 'Installs/Configures postfix'
source_url 'https://github.com/facebook/chef-cookbooks/'
supports 'centos'
supports 'debian'
supports 'oracle'
supports 'redhat'
supports 'ubuntu'
version '0.0.1'
